### ISSUE TITLE
[Qt]: qtquickcontrols not in "touch" mode (needed for copy/paste popup)

### ISSUE THREAD

**Issue by notmart** [blue-systems/pm-img#115]
qtquickcontrols normally change their behavior when touchscreen is present (like hiding scrollbars and show the little copy/paste popups).
However this doesn't happen on the phone.

The code that in QtQuickControls decides this is qquickcontrolssettings.cpp:
bool QQuickControlSettings::hasTouchScreen() const
{
// QTBUG-36007
#if defined(Q_OS_ANDROID)
    return true;
#else
    foreach (const QTouchDevice *dev, QTouchDevice::devices())
        if (dev->type() == QTouchDevice::TouchScreen)
            return true;
    return false;
#endif
}

this means QTouchDevice::devices() returns an empty list, or device of wrong type.

this i guess should come from the wayland platform integration plugin?

**Comment by mgraesslin** [comment]
if it comes from the QPA it looks strange as the ifdef would not be needed.

**Comment by notmart** [comment]
that comes from qtquickcontrols.

something related i see in the qpa is in QWaylandInputDevice::seat_capabilities
qtwayland/src/client/qwaylandinputdevice.cpp

where a QTouchDevice gets created (they're static trough the app, so i guess that code path should be hit first, then QTouchDevice::devices() from qtquickcontrols should return those created there)

**Comment by mgraesslin** [comment]
KWin properly announces that touch is supported. From hwcomposer backend:
waylandServer()->seat()->setHasTouch(true);

**Comment by notmart** [comment]
seems the problem is that the controls settings besides signaling to have touch also needs an "ismobile" property, that on linux is actually hardcoded, so we need a fork of it

**Comment by notmart** [comment]
that's wit some patches to qtquickcontrols http://imagebin.ca/v/28ahPi51oZI0
unfortunately i don't think is anything mergeable upstream, it would need some patches to be carried out in our package

**Comment by aleixpol** [comment]
Why isn't it mergeable? :/ can we move it into our QPT or such?

It looks good by the way.

**Comment by apachelogger** [comment]
Whatever needs packaging here?

**Comment by notmart** [comment]
it's all fine now as ass the needed patches have been pushed in to Qt
now scrollbars appear and disappear as expected on mobile devices, the inline edit menu appears to work
