### ISSUE TITLE
[kwayland]: mapping touch-to-mouse events for x11-clients

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#120]
applications that should work:
- gnome-chess
tested gnome-chess (sudo apt-get install gnome-chess):
game client opens in window and i  can now select a figure with white, but touch event seems to only work first time, so i cannot finish moving a piece, only selecting...

**Comment by star-buck** [comment]
@jriddell :
can you check the commit from notmart is actually packaged and in the latest IMG?

**Comment by notmart** [comment]
the commit id is cde26bc71c7148381e82799c17509966b03a93fb of kwayland repo

**Comment by mgraesslin** [comment]
possible fix in kwin: http://commits.kde.org/kwin/b8ae823b50a84e8c2355ed8dfb75cf18bd60a056

Please rebuild kwin

**Comment by jriddell** [comment]
waiting on mobile ci to re-appear

**Comment by star-buck** [comment]
triggered rebuild of kwin

**Comment by star-buck** [comment]
IMG 129: typing "gnome-chess" in konsole doesnt even start the game anymore (worked before)

**Comment by star-buck** [comment]
instead gnome-chess freezes the screen

**Comment by notmart** [comment]
right now x11 apps make kwin crash, however with the next packaging of the breeze window deco (weird but has to do about it) it should work: successfully managed to move pawns in gnome-chess ;)

**Comment by star-buck** [comment]
works, but still shaky: 
first touch to select a figure works consitently, but moving to a new field only works ~20% of the time...

as a clue for the first touch event to pick a figure, one can reproducably get this behaviour:
select a figure, then deselect it again by pressing again on the same figure.
Then selecting a new figure elsewhere on the baord activates precisely the former figure again, as if the third touch event is still executed on the former piece area.

@notmart : any idea how to improve this to work more reliable?

**Comment by notmart** [comment]
i changed it a bit faking a move before the touch. It seems to work better on the x86 system, let's see how will be on the phone

**Comment by star-buck** [comment]
this worked before, but with IMG11 seems to have stopped working.

**Comment by mgraesslin** [comment]
actually there is a better way now: we "just" need to ship Xwayland 1.18 (which got released last week). It now has proper support for touch events built in. I want to open a dedicated issue for that anyway.

**Comment by mgraesslin** [comment]
and created #217 for that.

**Comment by bhush9** [comment]
now xwayland 1.18 is shipped, marking as Read for QA.

**Comment by star-buck** [comment]
works.
