### ISSUE TITLE
[package]: screenshot app

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/pm-img#124]
Based on a small discussion yesterday on IRC I made it possible to use KWin's screenshot dbus interface with OpenGL ES 3.0. This is available in latest kwin master.

With that it's possible to create a fullscreen screenshot in the following way:
qdbus org.kde.KWin /Screenshot org.kde.kwin.Screenshot.screenshotFullscreen

The call returns the path where the file was created, e.g.:
/tmp/kwin_screenshot_T12709.png

A possible app could be just a desktop file which performs the dbus call or a with a small qml interface to set a screenshot delay.

**Comment by bhush9** [comment]
I've played little bit with it today

![screenshot app](https://ptpb.pw/QWc8.png)

Here is initial version, at moment of commenting it is very basic app

**Comment by bhush9** [comment]
Packagers please package it from : https://github.com/plasma-apps/screenshotapp

(I will eventually move it to kde git)

**Comment by star-buck** [comment]
shipped and kinda works
