### ISSUE TITLE
[Settings]: screen kcm: exiting crashes Settings

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#132]
you start the Settings app, you can enter any kcm and press the "X" close button just fine.
You enter the Screen kcm, then hit the close button and after 2-3 seconds of closing, a crash notice appears.

**Comment by sebasje** [comment]
Can't reproduce it here, any special steps you've taken?

**Comment by star-buck** [comment]
you start the Settings app, you can enter any kcm and press the "X" close button just fine.
You enter the Screen kcm, then hit the close button and after 2-3 seconds of closing, a crash notice appears.

**Comment by sebasje** [comment]
Got it, I can reproduce.

**Comment by star-buck** [comment]
img11: still crashes the same

**Comment by sebasje** [comment]
The bug should be fixed now, but it probably hasn't made it into the image yet.

**Comment by bhush9** [comment]
@sebasje : any specific commit?

**Comment by mgraesslin** [comment]
http://commits.kde.org/kscreen/4653c287f844f2cb19379ff001ca76d7d9e3a2a1

**Comment by mgraesslin** [comment]
which might not be the same, I misinterpreted this to be the kscreen kcm in systemsettings

**Comment by sebasje** [comment]
Yes, that's the commit I was thinking of. I had debugged this problem at some point, but couldn't figure out the cause, if I recall correctly, this seems to be the fix we needed. Let's try once package updates are available.

**Comment by star-buck** [comment]
fixed.
