### ISSUE TITLE
[kwinwrapper]: currently hardcodes arm, which is meh for amd64 builds

### ISSUE THREAD

**Issue by apachelogger** [blue-systems/pm-img#141]
kwinwrapper presently hardcodes armhf paths which is meh on amd64 builds:

> export  QML2_IMPORT_PATH=/usr/lib/arm-linux-gnueabihf/qt5/qml/:$QML2_IMPORT_PATH

probably kwinwrapper needs to be changed to a cmake configure_file file and then use dpkg-architecture to get the target architecture at build time. or instead of usign dpkg-architecture expect the callee (debian/rules) to tell it which path to use.

**Comment by bhush9** [comment]
What I see is this line is utterly useless.. there is no need to do any dpkg/cmake magic with it IMO.

Thing is QML2_IMPORT_PATH it specifies is already in qt's own qml import lookup path. So its just useless..

I just tested by removing this line locally and seems to work fine. I will remove this from upstream repo and close this issue when is packaged.

**Comment by bhush9** [comment]
Closing this now. I've removed that line long ago.
