### ISSUE TITLE
[networking] prefer wifi over GSM for data

### ISSUE THREAD

**Issue by sebasje** [blue-systems/pm-img#144]
When I'm connected to a broadband network and a wifi network, the mobile connection takes precedence in the routing table. We should make sure that wifi is preferred, as wifi is usually lower cost and higher bandwidth.

**Comment by bhush9** [comment]
Possible fix.

in, ``` /etc/NetworkManager/conf.d/51-prefer-wifi.conf ``` file,

```
[connection-wifi]
match-device=type:wifi
ipv4.route-metric=25
ipv6.route-metric=25

[connection-gsm]
match-device=type:gsm
ipv4.route-metric=50
ipv6.route-metric=50
```

**Comment by bhush9** [comment]
(Note: I didn't test this, please test first)

**Comment by sebasje** [comment]
Will test and report back here.

**Comment by bhush9** [comment]
IIRC @sebasje reported this was auto magically fixed for him on IRC.. can you confirm? Otherwise I will ship this configuration in next image.

**Comment by star-buck** [comment]
is it shipped? then please mark 'Ready'.

**Comment by bhush9** [comment]
I think this issue is fixed, and I haven't seen this recently.. so shipping that config doesn't seem to be required.
