### ISSUE TITLE
[ubuntu click-apps]: list of click apps

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#160]
How-to install: https://github.com/blue-systems/pm-img/issues/21#issuecomment-112996191

Sources: 
- https://core-apps-jenkins.ubuntu.com/
- http://people.canonical.com/~ubuntu-archive/click_packages/?C=M;O=D

**Installed: (click if its showing launcher + working)**
- [x] Stallboard: https://www.dropbox.com/s/vd1swwzbxaj0ihw/com.popey.stallboard_0.2_all.click?dl=0
- [x] com.ubuntu.calculator   2.0.233
- [ ] com.ubuntu.reminders    0.5.472
- [ ] com.ubuntu.clock        3.6.412
- [ ] com.ubuntu.music        2.3.964
- [ ] com.ubuntu.weather      3.1.182

**To be installed:**

**Won't work**
- ~~com.canonical.payui     15.01.140~~ (not really a app, but service AFAIU)
- ~~com.ubuntu.gallery      2.9.1.1260~~ (Won't work due to incompatible libhybris)
- ~~com.ubuntu.camera       3.0.0.616~~ (Same as above)

**Comment by star-buck** [comment]
not shipped as of IMG137

**Comment by star-buck** [comment]
@bhush9 : please include this default for now as testing app for 
* sound and 
* to see if click/mir apps still work

**Comment by bhush9** [comment]
Turns out it is already installed, just not showing up in launcher area.. will investigate

**Comment by bhush9** [comment]
Actually it is not getting installed at all..

```
15:00:09 + pkcon install-local file.click --allow-untrusted
15:00:09 Failed to contact PackageKit: Could not connect: No such file or directory
```

**Comment by star-buck** [comment]
The file on dropbox is there?
Have you followed this tutorial from @aleixpol : https://github.com/blue-systems/pm-img/issues/21#issuecomment-112996191 ?

**Comment by star-buck** [comment]
@bhush9 @aleixpol : please look into make that .click-app install again

**Comment by aleixpol** [comment]
For starters `packagekit-plugin-click` package is needed:
```
$ phablet@ubuntu-phablet:~$ pkcon install-local com.popey.stallboard_0.2_all.click
Installing files              [=========================]         _0.2_all.click 
Finished                      [=========================]         
Fatal error: MIME type 'application/x-click' not supported /home/phablet/com.popey.stallboard_0.2_all.click
$ sudo apt install packagekit-plugin-click
...
$ phablet@ubuntu-phablet:~$ pkcon install-local com.popey.stallboard_0.2_all.click
WARNING:root:debsig-verify not available; cannot check signatures
Cannot install /home/phablet/com.popey.stallboard_0.2_all.click: Framework "ubuntu-sdk-13.10" not present on system (use --force-missing-framework option to override)
```

This unveils another problem I'm not sure how to fix. Anybody knows what a `Framework "ubuntu-sdk-13.10"` is?

**Comment by star-buck** [comment]
Did we have this before while it was working?

**Comment by aleixpol** [comment]
I don't think I ever saw this error message.

**Comment by star-buck** [comment]
So the question is: Did we ship it previously?

**Comment by bhush9** [comment]
![image](https://cloud.githubusercontent.com/assets/1061944/12113331/04e97700-b3c8-11e5-8ea4-753266df5a08.png)

I got them working in theory, but requires some proper changes to get them working on mobile IMG.

**Comment by star-buck** [comment]
What changes exactly are needed?

**Comment by bhush9** [comment]
Mainly _something_ that makes them show up in our launcher, and instead of using pkcon using click command to install them.

That _something_ is using http://click.readthedocs.org/en/latest/hooks.html

**Comment by aleixpol** [comment]
Last time I checked, they were appearing in the menu. Do you know what changed, @bhush9?

**Comment by bhush9** [comment]
click apps that are shipped as deb do appear in menu fine but .click apps doesn't.

**Comment by star-buck** [comment]
Deb files are just that: .deb (not click?).
They all maybe ubuntu touch apps, but click is the package format?

**Comment by bhush9** [comment]
not sure I understood question?

**Comment by bhush9** [comment]
Ubuntu apps are either deb packages or .click packages.. deb packages gets shown into launcher as they ship desktop files in /usr/share/applications however .click applications are installed into /opt/click.ubuntu.com/ and don't install .desktop files where our launcher searches them. so they don't appear in our launcher

**Comment by star-buck** [comment]
Now you got it right :)

**Comment by star-buck** [comment]
We can also get official click apps from ubuntu from here:
https://core-apps-jenkins.ubuntu.com/job/filemanager-app-ci/

**Comment by bhush9** [comment]
rather more proper place : http://people.canonical.com/~ubuntu-archive/click_packages/

**Comment by star-buck** [comment]
nice!
@bhush9 : please try installing one of those click apps on latest xenial img:
e.g. http://people.canonical.com/~ubuntu-archive/click_packages/com.ubuntu.sudoku_1.1.382_all.click

**Comment by bhush9** [comment]
Installing click apps is not a problem, there are multiple click packages installed already.. see `click list`. Problem is we have no real way to show them in launcher and launch them.

**Comment by star-buck** [comment]
@notmart : any way to make installed .click apps icons appear in our launcher list?

**Comment by bhush9** [comment]
I've put together script in plasma-phone-dev-setup which looks for desktop files and puts them in ~/.local/share/applications with few edits.. This script takes argument of package name..

```
click-process com.popey.stallboard
```

Now it will appear in launcher list..

**Comment by bhush9** [comment]
Some packages are not supposed to work at all, modified ticket above.
