### ISSUE TITLE
[settings]: set default date to more recent than 1970

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#170]
the initial date after flashing should be somewhat recent, e.g. 1.1.2015

**Comment by sebasje** [comment]
timedatectl --set-time <somewhen this year>

should be done somewhen after flashing / first boot, that should be sufficient to allows SSL to work (which means initial package updates), and also the resize-root-partition script will work then, even without wifi set up previously.

**Comment by sebasje** [comment]
Okay, the following should be run on first start:

timedatectl set-ntp off
timedatectl set-time "2015-7-25 18:17:16"
timedatectl set-ntp on

**Comment by star-buck** [comment]
IMG 138: still 1970

**Comment by star-buck** [comment]
seems to work fine now
