### ISSUE TITLE
[IMG]: "sudo apt-get upgrade" wants to downgrades 16 qml/qt-packages

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#171]
The following packages have been kept back:
  ubuntu-touch-session
The following packages will be upgraded:
  bluez libbluetooth3 libmission-control-plugins0 libmtpserver1 libsqlite3-0
  qtdeclarative5-ubuntu-keyboard-extensions0.1
  qtdeclarative5-ubuntu-ui-extras-browser-plugin
  qtdeclarative5-ubuntu-web-plugin qtdeclarative5-ubuntu-web-plugin-assets
  sqlite3 telepathy-mission-control-5 ubuntu-keyboard-data webapp-container
  webbrowser-app
The following packages will be DOWNGRADED:
  qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
  qml-module-qtqml-models2 qml-module-qtqml-statemachine
  qml-module-qtquick-localstorage qml-module-qtquick-particles2
  qml-module-qtquick-window2 qml-module-qtquick-xmllistmodel
  qml-module-qtquick2 qmlscene qtdeclarative5-folderlistmodel-plugin
  qtdeclarative5-localstorage-plugin qtdeclarative5-particles-plugin
  qtdeclarative5-qtquick2-plugin qtdeclarative5-window-plugin
  qtdeclarative5-xmllistmodel-plugin
14 upgraded, 0 newly installed, 16 downgraded, 0 to remove and 1 not upgraded.
Need to get 2,668 kB of archives.
After this operation, 366 kB of additional disk space will be used.

**Comment by star-buck** [comment]
still as of IMG 138

**Comment by jriddell** [comment]
it's because we pin to prefer the mobile kci qt package but there's a newer version in launchpad which is installed on the image.  does it cause any problems?

**Comment by bhush9** [comment]
No longer happens now as we are using qt 5.5 from our CI.
