### ISSUE TITLE
[packaging]: move everything from LP ppa -> mobile.neon.pangea.pub

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#173]
So the idea was to no longer need to build stuff on LP:
https://launchpad.net/~plasma-phone/+archive/ubuntu/ppa/+packages

Can we therefore move the remaining packages from this ppa to mobile.neon.pangea.pub

Or is there a reason that somehow requires them to still be in the ppa?

**Comment by apachelogger** [comment]
Needs technology to build arbitrary things via jenkins first. Which has been on todo for like 5 months -.-

**Comment by bhush9** [comment]
I think, now we can safely remove at least this from this ppa:

- samegame : packaged on MobileKCI already
- consolekit(2) : I believe it was added to fix polkit issue mentioned in #130 but no longer required
- libepoxy : already in mobile CI
- voicecall and friends (libresource, libresourceqt) : voicecall dependency was removed from the plasma-phone-components quite sometime ago.
- qtwayland : we already build qt 5.5 on mobile CI

I don't have power to dump things..

**Comment by bhush9** [comment]
Things I am not sure about are:

- ubuntu-touch-session : why it is pinned to specific version?
- signon-ui : do we ship some specific patches?
- telepathy-mission-control : same question as signon-ui (maybe we can add them in CI?)
- libngf-qt : ????!
- dekko : ????!

**Comment by mck182** [comment]
signon-ui - yes, requires a special patch for vivid [1]
telepathy-mission-control - I believe that this also still requires a patch for vivid [2]

[1] - https://code.launchpad.net/~mardy/signon-ui/lp1473422
[2] - https://bugs.freedesktop.org/show_bug.cgi?id=91272 and https://bugs.launchpad.net/ubuntu/+source/telepathy-mission-control-5/+bug/1473011

**Comment by star-buck** [comment]
URL is no longer kci, but neon: http://mobile.neon.pangea.pub/

**Comment by star-buck** [comment]
@bhush9 : is this done or are there still things added to our IMGs via PPAs that we control?

**Comment by bhush9** [comment]
Unfortunately yes, still we need ppa, at least for ubuntu-touch-session and telepathy-mission-control-5

**Comment by star-buck** [comment]
cant we built the packages and put them into our own repo?
http://mobile.neon.pangea.pub/

**Comment by bhush9** [comment]
We need some patches on top of them, which means forking whole source package and later keeping them in sync when things change upstream. I would like to avoid them.. our CI have tech to build things as it is... but not with small patches.

**Comment by bhush9** [comment]
So... I've migrated away from the ubuntu-touch-session package, 20160727-062941 doesn't use PPA at all, previously 20160727-062941 attempted to do same, but failed because ubuntu-touch-session have extrausers pam config, which I've copied to plasma-phone-settings package now...

**Comment by bhush9** [comment]
I will proceed to delete PPA now, as it have all critical use-cases covered.

**Comment by star-buck** [comment]
ill close this here then
