### ISSUE TITLE
[apps]: openstreetmaps (OSM, Mapbox)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#18]

**Comment by sebasje** [comment]
May be based either on Marble, or on MapboxGL ( https://www.mapbox.com/blog/qmapboxgl/ )

**Comment by aleixpol** [comment]
I'd suggest to test:
import QtPositioning 5.2
import QtLocation 5.3

I've been playing around with it on kde:scratch/apol/citybikes-meego.git, works reasonably well.
* don't be fooled by the repository name, it's bare Qt5 code *

**Comment by star-buck** [comment]
ship this click app for Openstreetmap:
https://www.dropbox.com/s/ag51pokzymx29ug/com.popey.osm_0.7_all.click?dl=0

**Comment by star-buck** [comment]
@Riddell: please ship this with next IMG.

**Comment by bhush9** [comment]
we are shipping marble in our mobile IMG from quite sometime, this can be closed perhaps?

**Comment by star-buck** [comment]
yep
