### ISSUE TITLE
gltron: when starting via konsole, gfx shows up inside wayland window, when starting from launcher icon, it doesnt

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#183]

**Comment by mgraesslin** [comment]
Honestly I doubt that gltron can work properly at all on the phone. Given the dependencies it doesn't use sdl2, so it uses GLX, which is software emulated on the phone.

I would suggest to focus on things which can work (e.g. KDE's tron implementation ;-) ).

**Comment by star-buck** [comment]
The thing is not gltron. The thing is there is a difference launching it
from konsole and via icon, so this may be relevant to other apps too.
