### ISSUE TITLE
[IMG]: refer to kci-mobile IMG as neon-mobile

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#191]

**Comment by jriddell** [comment]
I've pushed the code to kde:mobster
rebranding will have to wait for e.v. to make up its mind in a ten days

**Comment by star-buck** [comment]
Any link?
Do we have a phabricator project for it?

**Comment by jriddell** [comment]
https://projects.kde.org/projects/playground/devtools/mobster
No phabricator for it yet, there's already bugs for it reported here so I wasn't wanting to add another bug tracker

**Comment by jriddell** [comment]
done as much as is sane for now

**Comment by star-buck** [comment]
Update Note:

Since we now have 
http://neon.pangea.pub
I following old kci logic and added 
http://mobile.neon.pangea.pub

**Comment by star-buck** [comment]
For now mobile.neon points to same server as mobile.kci.

**Comment by bhush9** [comment]
Is neon.pangea.pub down or doesn't point to anything yet? it says ERR_CONNECTION_REFUSED for me?

**Comment by star-buck** [comment]
neon.pangea.pub may not be setup completely serverside yet. but both domain and DO server exist.

**Comment by star-buck** [comment]
I also updated the flashing instructions here to read neon instead of kubuntu:
http://neon.plasma-phone.org/

Lets make sure it stays consistent with the next phone IMG update (keeping a screenshot saved for reference below):
![neon-mobile](https://cloud.githubusercontent.com/assets/840070/12011890/60a2bd4c-ac96-11e5-8c62-fa70fee12854.png)

**Comment by star-buck** [comment]
maybe replace string "ubuntu" in 
"Latest available Image: ubuntu=2015...." 
also with "neon"?

**Comment by bhush9** [comment]
We can change it in website, but internally it will still be called ubuntu=.. as this variable is used by ubuntu-device-flash internally.

**Comment by star-buck** [comment]
Okay, thats fine internally, so if it doesnt interfere with that, lets
change it visibly on website only.

**Comment by star-buck** [comment]
closing this for now
