### ISSUE TITLE
[wallpaper dialog]: doesnt show thumbnail preview of available wallpapers

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#198]

**Comment by bhush9** [comment]
Requires kio-extras to be installed but somehow.. installing it removes things

The following extra packages will be installed:
  kio-extras-data
The following packages will be REMOVED:
  kdeconnect-plasma kinfocenter plasma-mobile plasma-phone plasma-phone-components plasma-settings plasma-workspace
The following NEW packages will be installed:
  kio-extras kio-extras-data

Not sure :open_mouth:

**Comment by jriddell** [comment]
installed as part of 20150924.130033 image
