### ISSUE TITLE
KAccounts packaging adjustment

### ISSUE THREAD

**Issue by mck182** [blue-systems/pm-img#209]
Things got moved around a bit, basically, kaccounts-providers got a new plugin to install, kaccounts-integration lost some plugins and kaccounts-mobile needs packaging. Here's a full list of changes:

Out of kaccounts-integration repo:
src/daemon/plugins/google -> kaccounts-mobile:google/google-contacts-sync
src/daemon/plugins/owncloud -> kaccounts-mobile:common/carddav-contacts-sync
src/owncloud -> kaccounts-providers:plugins/owncloud-ui

Out of kaccounts-providers repo:
services/owncloud-contacts.service.in -> kaccounts-mobile:services/owncloud-contacts.service.in
services/disabled/google-contacts.service.in -> kaccounts-mobile:services/google-contacts.service.in

**Comment by bhush9** [comment]
This seems to be done.. please verify everything is fine.. I will add kaccounts-mobile in next image.

**Comment by bhush9** [comment]
Available in IMG13.

**Comment by star-buck** [comment]
img18 has kaccounts package reported missing under Settings -> Accounts

**Comment by bhush9** [comment]
kaccounts-mobile itself is properly packaged, however plasma-settings is missing dep to qml-module-ubuntu-onlineaccounts (installing will fix that, I will change packaging for that)

**Comment by star-buck** [comment]
Closing then here.
