### ISSUE TITLE
LTS: click-packages

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#21]
How-to download:

```
curl https://raw.githubusercontent.com/plasma-mobile/xutils/master/click-get
sudo apt install python-requests-oauthlib python3-requests-oauthlib
chmod a+x click-get
./click-get <anyurl>
```
Example:
./click-get https://public.apps.ubuntu.com/download/com.popey/stallboard/com.popey.stallboard_0.2_all.click
user: hansi.hinterseer@t-online.de / 12345678 

How-to install a .click file:
```
pkcon install-local .CLICK-FILENAME --allow-untrusted
```

Good info about click vs. Deb:
https://lwn.net/Articles/565521/

video with some more insight about ubuntu click: 
https://www.youtube.com/watch?v=h1anchaDI-E

Spanish Click App-Store:
http://ubuntuphone.es/app-store/

Examples for testing: 
http://ubuntuphone.es/app-store/app/com.popey.stallboard
http://ubuntuphone.es/app-store/app/com.ubuntu.filemanager
http://ubuntuphone.es/app-store/app/com.popey.osm
http://ubuntuphone.es/app-store/app/com.ubuntu.developer.nikwen.cantata-touch
http://ubuntuphone.es/app-store/app/com.ubuntu.developer.bobo1993324.qvbam

**Comment by star-buck** [comment]
Example: 
Ubuntu Touch .click-format: http://ubuntuphone.es/app-store/app/com.ubuntu.scopes.soundcloud

**Comment by star-buck** [comment]
Good info about click vs. Deb:
https://lwn.net/Articles/565521/

**Comment by aleixpol** [comment]
Installing without root password would be also good from an SDK PoV. We can't specify the password if we call "adb shell sudo dpkg -i mypkg.deb".

**Comment by star-buck** [comment]
video with ome more insight about ubuntu click: 
https://www.youtube.com/watch?v=h1anchaDI-E

**Comment by star-buck** [comment]
Spanish Click App-Store:
http://ubuntuphone.es/app-store/

**Comment by aleixpol** [comment]
To install a click file:
```
pkcon install-local file.click --allow-untrusted
```

Look for desktop files in:
```
#username/appname/appname.desktop
/opt/click.ubuntu.com/.click/users/*/*/*.desktop
/usr/share/click/preinstalled/.click/users/*/*/*.desktop
```

Still need to see how to execute the applications.

**Comment by aleixpol** [comment]
Running an application is done by:
```
ubuntu-app-launch messaging-app
```
It works on the ubuntu phone, doesn't work on my Kubuntu mobile image.

**Comment by aleixpol** [comment]
Been playing a bit further, my conclusion is that click already works, but we need to be able to integrate applications written in click.

A first step will be to include ```/userdata/user-data/phablet/.local/share/applications/``` in the launcher list. This won't work on all applications though (e.g. the gallery app) because to execute the applications they use ```aa-exec-click``` that checks whether it's running Mir. This will make the desktop files not to work sometimes. Nevertheless, some applications such as the one described below will just work.

For further research, here's how to fetch a random click file:
```
from oauthlib.oauth1.rfc5849 import Client
import requests

# curl https://login.ubuntu.com/api/v2/tokens/oauth -d '{"email": "aleixpol@kde.org", "password": "<password>", "token_name": "click_example"}' -H 'Content-Type: application/json'
#{
    #"openid": "myGdLpz",
    #"token_name": "click_example",
    #"date_updated": "2015-06-18T00:21:09.109",
    #"token_key": "XLWbzoFAgX5Hdg0ViNS9pd55wYdH7THdIOaSVPaphtiONjnKSE02JagonMx6",
    #"consumer_secret": "7CyRE2o10a3ji7Or5QdkRET4mORPHpBcZdgVrv8l1pdEfqRIFv",
    #"href": "/api/v2/tokens/oauth/XLWbzoFAgX5Hdg0ViNS9pd55wYdH7THdIOaSVPaphtiONjnKSE02JagonMx6",
    #"date_created": "2015-06-18T00:21:09.109",
    #"consumer_key": "myGdLpz",
    #"token_secret": "0d5hQOhUuQ3U5oOmqs2Nbmy8lcBrL0PfDko51BRFUoPq4mXen57rGNmjxe7oVyAdCLlQ43"
#}

client = Client(
    "myGdLpz",  # consumer_key
    "7CyRE2o10a3ji7Or5QdkRET4mORPHpBcZdgVrv8l1pdEfqRIFv",  # consumer_secret
    "XLWbzoFAgX5Hdg0ViNS9pd55wYdH7THdIOaSVPaphtiONjnKSE02JagonMx6",  # token_key
    "0d5hQOhUuQ3U5oOmqs2Nbmy8lcBrL0PfDko51BRFUoPq4mXen57rGNmjxe7oVyAdCLlQ43"  # token_secret
)
uri, headers, body = client.sign("https://public.apps.ubuntu.com/download/net.launchpad.click-webapps/xkcd/net.launchpad.click-webapps.xkcd_5_all.click")

response = requests.get(uri, headers=headers)

with open("net.launchpad.click-webapps.xkcd_5_all.click", "wb") as f:
     f.write(response.content)
```

**Comment by aleixpol** [comment]
@notmart maybe we want to integrate the applications directory into the home screen lookup path?

**Comment by aleixpol** [comment]
So thing is it's already in the look-up path, even though it doesn't work at the moment, because it's using aa-exec-click. The only reason why it's not working is because there's a hook that modifies the desktop file to ensure it's going to be executed under apparmor.

Here it gets messy:
* We can disable the apparmor hook. Hooks can be edited with ```find /usr -name "*\.hook"``` and disabled, theoretically with ```click hook remove ubuntu-app-launch-desktop run-system```. Only that in practice it doesn't work, or I haven't been able to.
* We can fix apparmor so that applications get to be launcher properly. Now this sounds very reasonable, since we'll be leveraging an interesting technology anyway, in principle. I've spent about 3h trying to make it work, but didn't manage. What we need is to make sure the application can connect to ```/run/user/<pid>/wayland-0```, should be easy but I wasn't able to alter the behavior work.

**Comment by aleixpol** [comment]
We did some progress, with the help of @apachelogger. Saving here, just in case I might flash my phone:
```
phablet@ubuntu-phablet:~$ cat /etc/apparmor.d/abstractions/wayland
owner /run/user/*/wayland-0 rw,
owner /run/user/*/weston-shared-* rw,
owner /tmp/wayland-shm-* rw,
```
Still, will need to keep whitelisting stuff.

**Comment by aleixpol** [comment]
I just ran the first click-based application. That was the calculator, which is bundled with Ubuntu Phone.

Things to be done:
* Add the file specified on the comment before.
* ```echo "#include <abstractions/wayland>" >> /etc/apparmor.d/abstractions/base```
* prevent aa-exec-click from closing if there's some .X stuff.
```
phablet@ubuntu-phablet:/usr/share/click/preinstalled/com.ubuntu.calculator/2.0.182$ diff /usr/bin/aa-exec-click.original /usr/bin/aa-exec-click
54c54
<         exit 1
---
> #        exit 1
```

**Comment by star-buck** [comment]
@apachelogger :
please find a way of shipping for next IMG and add small comment on how / where its done.

**Comment by star-buck** [comment]
test app:
http://ubuntuphone.es/app-store/app/com.popey.stallboard

**Comment by star-buck** [comment]
testing this from the es-appstore:
http://ubuntuphone.es/app-store/app/com.ubuntu.filemanager

**Comment by apachelogger** [comment]
jon something for you to look at in the morning

we'll need the abstractions/wayland file packaged. that package probably also needs to dpkg-divert abstractions/base and add an include on wayland and divert aa-exec-click and somehow get rid of the exit.

it's slightly shite really.

alternatively for aa-exec-click we could probably fork the source and apt-hold it, I understand this hack is supposed to go away eventually anyway.

the apparmor abtractions stuff is here to stay though I fear.

**Comment by star-buck** [comment]
@jriddell : can you have a look and try get that packaged + updated here:
http://mobile.kci.pangea.pub/pool/main/

**Comment by jriddell** [comment]
plasma-phone-settings-packaging and plasma-phone-settings updated, waiting on mobile ci to reappear to update

**Comment by star-buck** [comment]
Jonathan:
Can you check with Harald or have a look at the server yourself?
The server itself seems to be up and running fine, not sure if the :8080
pointed to another server or if something on the server needs to be started
for jenkins to come up again?

**Comment by star-buck** [comment]
Should be fixed, waiting for jenkins to fully come up again...

**Comment by star-buck** [comment]
triggered rebuilding:
- plasma-phone-settings
- plasma-phone-settings-packaging

**Comment by notmart** [comment]
the new file is correctly here, but it still needs some files installed by upstream packages to be patched: how that should be done?

**Comment by aleixpol** [comment]
@star-buck asked for a testing tool, this puts together what I had on the previous snippet to be used directly.
https://raw.githubusercontent.com/plasma-mobile/xutils/master/click-get

Use as: ./click-get <anyurl>

**Comment by bhush9** [comment]
considering IMG27 ships click packages and they somewhat works.. we should close this

**Comment by star-buck** [comment]
lets keep this open for info, its LTS, meaning Long Term Solution

**Comment by star-buck** [comment]
closing.
