### ISSUE TITLE
IMG11: no sound

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#210]
no sound is played in img11, testing e.g. "animal-farm"

**Comment by bhush9** [comment]
Some important package got removed, thats why oh its gorgeous is also not playing.. Now that I am back from vacation, I will look into it.

**Comment by star-buck** [comment]
is sound now working?

**Comment by bhush9** [comment]
no, I haven't managed to find which package causes sound to not working, tried various combinations.. will investigate more.

**Comment by bhush9** [comment]
yey... found that alsa-base, linux-sound-base and pulseaudio-module-droid packages needs to be installed. Updated mobster code, will be working in next IMG13

**Comment by bhush9** [comment]
Fixed with IMG13
