### ISSUE TITLE
[HWComposer]: fix tearing problem

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#216]
kwin tears when scrolling (when rapidly scrolling through the list of applications, a line is visible in the middle of the screen, with content 1 frame ahead)

**Comment by star-buck** [comment]
transferred this ticket out of an old summary ticket, not sure if thats still valid or can be closed...

**Comment by bhush9** [comment]
It is fixed with recent kwin.. (Not in IMG11 by default, but upgrade should bring it)

**Comment by star-buck** [comment]
okay. since the current img11 looks much better with regrads to previous tearing, closing this now.
