### ISSUE TITLE
[XWayland]: Provide XWayland 1.18

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/pm-img#217]
Please provide the latest XWayland server (1.18) in the image. It got released last week and brings important improvements for X11 applications like touch support.

**Comment by bhush9** [comment]
Is it available in some ppa or something?

**Comment by mgraesslin** [comment]
I do not know but Debian experimental has (working) packages.

**Comment by star-buck** [comment]
do we have packages ready for shipping in v13?

**Comment by bhush9** [comment]
Unfortunately not yet.. There are no packages available for xwayland 1.18, there are xorg server git ppa named "X crackers" but it doesn't provide xwayland..

**Comment by star-buck** [comment]
@bhush9 : please see that this gets packaged now in our own repo and shipped with next img.

**Comment by bhush9** [comment]
xwayland | 2:1.18.0-2kubuntu1 | vivid | amd64, armhf

**Comment by bhush9** [comment]
IMG18 have it
