### ISSUE TITLE
[taskbar]: shopping bag icon shown instead of task icon

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#221]

**Comment by eikehein** [comment]
App name, Plasma version, screenshot ...?

**Comment by notmart** [comment]
that icon used to be the same as in kickoff, so now it uses the new one...
i guess a separate icon named "window-list" or something like that is needed

**Comment by bhush9** [comment]
It is using "applications-other" icon.. dunno why designer decided to replace it with shopping bag..

**Comment by notmart** [comment]
I added a window-list icon in plasma-framework (should look like the old one) and changed it in plasma-phone-components, rebuilding those 2 packages should fix it

**Comment by bhush9** [comment]
Fixed in IMG13
