### ISSUE TITLE
reintegrate Qt patches in our Qt build

### ISSUE THREAD

**Issue by notmart** [blue-systems/pm-img#226]
the two patches needed are:
https://codereview.qt-project.org/#/c/121709/
https://codereview.qt-project.org/#/c/121659/
revision
3660cd60e9a8f74203b2eefef23f4baa383f75c3
in qtquickcontrols
there may be other ones, that's what i can think about for now

**Comment by bhush9** [comment]
> https://codereview.qt-project.org/#/c/121709/
> https://codereview.qt-project.org/#/c/121659/

This two are added.. will add 3660cd60e9a8f74203b2eefef23f4baa383f75c3 in tomorrow morning

**Comment by bhush9** [comment]
done..
