### ISSUE TITLE
[plasma]: starting app sometimes crashes plasma, so app appears fullscreen with no taskbar and topbar

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#233]
some apps seem fine, others dont start at all, while others seem to crash plasma. 
koko starting fine but crashing plasma seems at least consitently reproducible for img14 though?

**Comment by bhush9** [comment]
doesn't start itself fullscreen but plasmashell seems to be crashing.. so panels get away.

**Comment by star-buck** [comment]
okay, thats slightly better ;)

**Comment by bhush9** [comment]
also this is not related to koko.. any app launching crashes plasma sometimes.

**Comment by aleixpol** [comment]
I've experienced that testing Discover as well.

**Comment by star-buck** [comment]
some apps seem fine, others dont start at all, while others seem to crash plasma. 
koko starting fine but crashing plasma seems at least consitently reproducible for img14 though?
