### ISSUE TITLE
[Settings]: doesnt start

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#234]

**Comment by bhush9** [comment]
plasma-mobile:962e592afdf2a3f716a36aa370c7fbcaa6 removed Package, dunno where that is placed now? this is causing system settings to not start.

**Comment by bhush9** [comment]
https://phabricator.kde.org/D729

**Comment by bhush9** [comment]
Fixed now.

**Comment by star-buck** [comment]
starts fine on neon17
