### ISSUE TITLE
[document viewer]: doesnt start

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#237]
img14

**Comment by bhush9** [comment]
Seems to be missing git add.. https://quickgit.kde.org/?p=okular.git&a=commit&h=2b4486a00de34cf0102997db8bb88462d4959de6 OkularDrawer.qml file is missing.

**Comment by notmart** [comment]
eew, my bad then :/
will fix as soon as i get home next couple of days

**Comment by notmart** [comment]
repackaging

**Comment by bhush9** [comment]
Seems to work now.

**Comment by star-buck** [comment]
neon17: still doesnt start

**Comment by bhush9** [comment]
problem above was fixed, this is new problem that pop up :p

**Comment by bhush9** [comment]
erm, which document viewer did you start? there are two now?

**Comment by star-buck** [comment]
ours, not ubuntu

**Comment by llelectronics** [comment]
Turns out folderlistmodel qml plugin is missing. Installing it and the okular document viewer works.

**Comment by bhush9** [comment]
will fix packaging.

**Comment by bhush9** [comment]
adjusted packaging in : https://github.com/plasma-phone-packaging/okular/commit/6a171e760667d22a854335a19c1e76e80e988adb will be fixed in next image.

**Comment by star-buck** [comment]
fixed
