### ISSUE TITLE
[animal farm]: no sound

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#239]
seems the animals make no sound.

**Comment by bhush9** [comment]
umm, works for me?

**Comment by star-buck** [comment]
odd... no sound here :musical_score:

**Comment by aleixpol** [comment]
Sound doesn't work here either.

**Comment by bhush9** [comment]
notmart | bshah: bah, finally managed to reproduce the black battery thing on the aptop, hopefully i know what is it     
     bshah | getting it reproduced on laptop means almost fixed                                                             
  notmart_ | in that magic of going around looking for parents i only consider qquickitems, but i'm doing it from a qobject 
  notmart_ | so yeah, it loses a piece

**Comment by bhush9** [comment]
err ignore

**Comment by bhush9** [comment]
its really odd, it works for me.. but maybe I did upgrade and installed packages afterwards.. will reflash and check whats wrong.

**Comment by bhush9** [comment]
hmm, missing dep : gstreamer1.0-plugins-ugly

install it and animals will make noise..

**Comment by star-buck** [comment]
good to know.
will mark it solved and close after shipping in next img also works.

**Comment by bhush9** [comment]
img18
