### ISSUE TITLE
[top panel]: missing battery icon

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#240]

**Comment by bhush9** [comment]
notmart | bshah: bah, finally managed to reproduce the black battery thing on the aptop, hopefully i know what is it     
     bshah | getting it reproduced on laptop means almost fixed                                                             
  notmart_ | in that magic of going around looking for parents i only consider qquickitems, but i'm doing it from a qobject 
  notmart_ | so yeah, it loses a piece

**Comment by notmart** [comment]
it's there but due to a problem it's a black battery on black background, i'm on it now

**Comment by star-buck** [comment]
:black_large_square:  :)

**Comment by bhush9** [comment]
recent plasma-framework fixed this.
