### ISSUE TITLE
[wifi]: after reboot wants password to retype in popup

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#242]
after first successfull connection and reboot, does not (auto-)connect again

**Comment by star-buck** [comment]
i see the reason now:
popup opening in the background (behind dropped down toppanel) is asking for the password again.

**Comment by mck182** [comment]
This is caused by kwallet timing out; bug introduced in kwallet commit 1d0bec904dd78ff21d1d68e9c3e363ad1a77f7ed.

I'm investigating.

**Comment by mck182** [comment]
Fixed in kwallet; http://commits.kde.org/kwallet-framework/901c27ca7cb05cca1a960747b280d40cd7707158

**Comment by bhush9** [comment]
Package available now : 5.18.0+git20160109.0454+15.04-0

**Comment by star-buck** [comment]
it seems still not reconnecting without popup in img18...

**Comment by star-buck** [comment]
okay, weird... it didnt for the first time when entering the password over the tiny field in the toppanel, but did so when entering the password a second time in the popup.

**Comment by star-buck** [comment]
seems somewhat working, at least the popup comes up in background but wifi is established nevertheless.
