### ISSUE TITLE
libappstreamqt0 should be compiled against Qt5

### ISSUE THREAD

**Issue by aleixpol** [blue-systems/pm-img#243]
As of recently, Discover QApt backend depends on Appstream. The appstreamqt provided by Ubuntu Vivid depends on Qt 4 and Discover uses Qt5.

It would be really convenient if we could get the Qt5 version as otherwise we can't link against it.

To that end, we'd need a newer version, since the available one is 0.7.4 which is too old for us.

**Comment by bhush9** [comment]
appstreamqt itself is recompiled now against qt5.5 however due to discover->plasma-discover rename it won't build.

**Comment by star-buck** [comment]
any idea to fix this?

**Comment by bhush9** [comment]
I've recompiled appstreamqt against our qt5. However currently kubuntu packagers are working on discover -> plasma-discover so it will need little time before I can build discover against new appstreamqt.

**Comment by bhush9** [comment]
Now plasma-discover starts.

**Comment by bhush9** [comment]
I am closing this, since this was required for vivid and in xenial it starts fine.
