### ISSUE TITLE
[wallpaper dialog]: pressing on empty area in homescreen brings up empty overlay

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#246]
img18

**Comment by notmart** [comment]
this seems related to another problem: that overlay is supposed to be there, with a toolbar at the bottom of the screen with "configure wallpaper" and "add widgets" buttons: however the panel geometries seems to be reported incorrectly and that toolbar ends up being hidden by the bottom panel, leaving that weird dark area

**Comment by notmart** [comment]
latest plan is 9th february
https://wiki.qt.io/Qt-5.6-release

**Comment by star-buck** [comment]
@notmart :
so qt5.6 will fix this? what part of qt is at fault here?

**Comment by notmart** [comment]
ah, sorry. I had answered actually to the wrong issue, the answer was for the scrollwheel one.

the wrong struts was actually our problem and is fixed, updating the packages (or waiting next image) will. fix it

**Comment by star-buck** [comment]
fixed with IMG20/xenial
