### ISSUE TITLE
[package request] Build telepathy-accounts-signon

### ISSUE THREAD

**Issue by mck182** [blue-systems/pm-img#247]
This is needed to get KAccounts accounts into Telepathy.

There is a buntu package but in any case here's the latest release

https://gitlab.com/accounts-sso/telepathy-accounts-signon/repository/archive.tar.gz?ref=1.0

**Comment by bhush9** [comment]
telepathy-accounts-signon | 1.0+git20160120.0853+15.04-0 | vivid | amd64, armhf, source

fresh from git.

**Comment by mck182** [comment]
Works.

**Comment by mck182** [comment]
Btw. the process mission-control-5 must be restarted after installing this package, otherwise the user will be required to reboot his phone.

So perhaps that should be added to the post-inst of the package or something.

**Comment by bhush9** [comment]
Closing this as discussed with @mck182 yesterday
