### ISSUE TITLE
[close button]: apps are still open and running in background...now its just like home button

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#249]
IMG20/xenial

**Comment by bhush9** [comment]
Umm, can't reproduce.. any specific app?

**Comment by star-buck** [comment]
You open an app, press X button and then press taskmanager button and see
it still running?

**Comment by bhush9** [comment]
Nope, can't reproduce. Tried with konsole, document viewer, peruse, settings etc.

**Comment by star-buck** [comment]
Now thats odd :)
I completely wiped and reflashed with img20 and thats what it does with all
of the above apps :)
Anyone else can try and report back?

**Comment by notmart** [comment]
I've seen it happening sometimes (pretty random) will investigate

**Comment by notmart** [comment]
should be fixed in master

**Comment by star-buck** [comment]
works
