### ISSUE TITLE
qtvirtualkeyboard issues

### ISSUE THREAD

**Issue by bhush9** [blue-systems/pm-img#253]
Just keeping track of things

- [x] By default it is not enabled and one need to enable it from drawer
- [x] Freezes plasmashell at start up.. possibly due to SNI item
- [x] Focusing krunner search bar in plasmashell crashes it
- [x] Enters text only in caps.
- [ ] Find a way to adjust its size

Due to first 4 issues, I've disabled it in image for now.

**Comment by bhush9** [comment]
If someone wants to experiment with it, edit /etc/enviroment and remove QT_IM_MODULE=maliit line from it, and then reboot.. After that enable it from top panel.

**Comment by mgraesslin** [comment]
First item is caused by the patch to KWin to workaround a QtWayland problem.

**Comment by bhush9** [comment]
Since all of issues are solved I am closing this one..
