### ISSUE TITLE
[IMG]: add more default space to root /-partition

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#36]

**Comment by jriddell** [comment]
using dd from /dev/zero made gzip go OOM on the image untar part of process
using dd from /dev/urandom made thrift server crap out
using fallocate of 1GB size made gzip OOM 
using fallocate of 10x100MB size made phone not boot
so I guess I need to experiment with different sizes of file to see what doesn't break

**Comment by star-buck** [comment]
any idea to increase the / partition?
as of IMG119 it looks like this:
'''/dev/loop0                      2.0G  1.6G  276M  86% /
/dev/mmcblk0p28           13G  3.4G  8.6G  29%  /home'''

**Comment by jriddell** [comment]
adding empty fallocate files doesn't do anything, they just take up space without making the device bigger, we need to work out what is making that loopback device and how to make it bigger by default

**Comment by star-buck** [comment]
this has become a problem now, one cannot install anything else nor upgrade as of current IMG (135):
[IMG]: root /-partition is 100% full

We need to find a method to make more space on the partition after reboot.

**Comment by star-buck** [comment]
any new ideas on this?

**Comment by bhush9** [comment]
One thing I noticed lately are apt archives.. When we upgrade with apt downloaded files are not cleaned.. Which turns out to be wasted space.. Can we somehow ship some config so that archives are deleted when upgrades are finished..??

**Comment by bhush9** [comment]
So, I researched bit about how to get more space initially, I realized its system-image-upgrader in the  recovery.img which defines the initial rootfs space.. I've created a recovery.img which would create rootfs of 4GB instead of 2GB default.

To use that,

```
wget http://neon.plasma-phone.org/recovery.img
ubuntu-device-flash --server="http://neon.plasma-phone.org/" touch --channel="neon-mobile/devel-proposed" --bootstrap --recovery-image recovery.img --developer-mode --password 1234
```

Here I added *--recovery-image recovery.img* in older command. If you get error like,

```
unknown flag `recovery-image'
```

You will need newer version of ubuntu-device-flash, for that.

```
sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
sudo add-apt-repository ppa:phablet-team/tools 
sudo apt-get update; sudo apt-get install ubuntu-device-flash
```

**Comment by bhush9** [comment]
Actually ignore that... that recovery image is somehow broken and doesn;t work... :-(

**Comment by bhush9** [comment]
Since we switched stack and now we no longer use dedicated system.img/ubuntu.img (ubuntu touch mechanism) file as rootfs this is no longer relevant. Closing this.
