### ISSUE TITLE
[Settings]: Time and Date: crashes Settings dialog when going back to main menu

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#53]

**Comment by star-buck** [comment]
time after fresh installation still set to 1970?

**Comment by sebasje** [comment]
The initial time setting has to be done differently, that's out of scope for this KCM (but obviously related). Perhaps the job of an installer?

The time setting has to be applied directly though. This works on the desktop, and it seems the signal to update all the clocks is fired, but not received, so clocks just update after the next minute when their internal timer fires and tells them to update the time. I'll look into it.

**Comment by star-buck** [comment]
doesnt crash anymore
