### ISSUE TITLE
[Settings]: Appearance: option to change background image

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#9]

**Comment by notmart** [comment]
the wallpaper dialog now has an "add wallpaper" button that shows a dialog with a list of wallpapers from the ~/Pictures folder, it makes at least easier to add custom wallpapers on the device.

It's still not perfect in many ways, besides being maybe desiderable to set it from other applications (quite a difficult problem)
we probably want to make dialogs like that a frameworksintegration plugin that replaces the standard KDE file picker dialog with something that just shows a list of "all the pictures" "all the songs" etc.

**Comment by star-buck** [comment]
can we add this also to some kcm, so the wallpaper becomes changeable additionally from Settings?
